/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/
import * as React from 'react';

import { IBuyboxViewProps } from '@msdyn365-commerce-modules/buybox/dist/types';
import {
    IBuyboxAddToCartViewProps,
    IBuyboxAddToWishlistViewProps,
    IBuyboxFindInStoreViewProps,
    IBuyboxProductConfigureDropdownViewProps,
    IBuyboxProductConfigureViewProps,
    IBuyboxProductQuantityViewProps
 } from '@msdyn365-commerce-modules/buybox/dist/types/modules/buybox/components';
import { Module, Node } from '@msdyn365-commerce-modules/utilities';
import { IBuyboxProps } from '../definition-extensions/buybox.ext.props.autogenerated';

const _renderAddToCart = (addToCart: IBuyboxAddToCartViewProps): JSX.Element => {
    const { ContainerProps, errorBlock, button } = addToCart;

    return (
        <Node {...ContainerProps}>
            {errorBlock}
            {button}
        </Node>
    );
};

const _renderAddToWishlist = (addToWishlist: IBuyboxAddToWishlistViewProps): JSX.Element => {
    const { ContainerProps, errorBlock, button } = addToWishlist;

    return (
        <Node {...ContainerProps}>
            {errorBlock}
            {button}
        </Node>
    );
};

const _renderConfigureDropdown = (dropdown: IBuyboxProductConfigureDropdownViewProps): JSX.Element => {
    const { ContainerProps, LabelContainerProps, heading, errors, select } = dropdown;

    return (
        <Node {...ContainerProps}>
            <Node {...LabelContainerProps}>
                {heading}
                {errors}
            </Node>
            {select}
        </Node>
    );
};

const _renderConfigure = (configure: IBuyboxProductConfigureViewProps): JSX.Element => {
    const { ContainerProps, dropdowns } = configure;

    return (
        <Node {...ContainerProps}>
            {dropdowns.map(_renderConfigureDropdown)}
        </Node>
    );
};

const _renderFindInStore = (findInStore: IBuyboxFindInStoreViewProps): JSX.Element => {
    const { ContainerProps, storeSelector, heading, description, errors, button } = findInStore;

    return (
        <Node {...ContainerProps}>
            {storeSelector}
            {heading}
            {description}
            {errors}
            {button}
        </Node>
    );
};

const _renderQuantity = (quantity: IBuyboxProductQuantityViewProps): JSX.Element => {
    const { ContainerProps, LabelContainerProps, heading, input, errors } = quantity;

    return (
        <Node {...ContainerProps}>
            <Node {...LabelContainerProps}>
                {heading}
                {errors}
            </Node>
            {input}
        </Node>
    );
};

const BuyboxView: React.FC<IBuyboxViewProps & IBuyboxProps<{}>> = props => {
    const { ModuleProps, ProductInfoContainerProps, addToCart, addToWishlist, configure, description, findInStore, quantity, price, title, rating } = props;

    return (
        <Module {...ModuleProps}>
            {props.mediaGallery}
            <Node {...ProductInfoContainerProps}>
                {title}
                {price}
                {configure && _renderConfigure(configure)}
                {quantity && _renderQuantity(quantity)}
                {props.slots.content && <div>{props.slots.content}</div>}
                {addToCart && _renderAddToCart(addToCart)}
                {addToWishlist && _renderAddToWishlist(addToWishlist)}
                {description}
                {rating}
                {findInStore && _renderFindInStore(findInStore)}
            </Node>
        </Module>
    );
};

export default BuyboxView;
