/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

// import * as Msdyn365 from '@msdyn365-commerce/core';
import { IFeaturedLayoutItemData } from './featured-layout-item.data';
import { IFeaturedLayoutItemProps } from './featured-layout-item.props.autogenerated';

/**
 *
 * FeaturedLayoutItem component
 * @extends {React.PureComponent<IFeaturedLayoutItemProps<IFeaturedLayoutItemData>>}
 */
export default class FeaturedLayoutItem extends React.PureComponent<IFeaturedLayoutItemProps<IFeaturedLayoutItemData>> {
    public render(): JSX.Element {
        const {
            config: {
                categoryLink, bgImage, heading, showButton
            }
        } = this.props;

        /*console.log('TheProps',this.props);
        const imageProps = {
            gridSettings: this.props.context.request.gridSettings || {},
            imageSettings: bgImage && bgImage.imageSettings
        };*/

        return (
            <div className='featured-layout-item'>
                <img src={bgImage} alt={categoryLink.linkText}/>
                <div className='featured-content'>
                    <h3>{heading}</h3>
                    {showButton &&
                        <a className='btn btn-light' href={categoryLink.linkUrl && categoryLink.linkUrl.destinationUrl}>{categoryLink.linkText}</a>}
                </div>
                <a className='featured-link' role='button' href={categoryLink.linkUrl && categoryLink.linkUrl.destinationUrl} />
            </div>
        );
    }
}
