/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { buildMockModuleProps} from '@msdyn365-commerce/core-internal';
/// <reference types="jest" />

// tslint:disable-next-line:no-unused-variable
import * as React from 'react';
import * as renderer from 'react-test-renderer';

import SampleMessage from '../sample-message';
import { ISampleMessageData } from '../sample-message.data';
import {
  ISampleMessageConfig,
  ISampleMessageProps
} from '../sample-message.props.autogenerated';

const mockData: ISampleMessageData = {
  actionResponse: {
    text: 'Sample Response Data'
  }
};

const mockConfig: ISampleMessageConfig = {
  showText: 'sample-message'
};

const mockActions = {};

describe('SampleMessage', () => {
  let moduleProps: ISampleMessageProps<ISampleMessageData>;
  beforeAll(() => {
    moduleProps = buildMockModuleProps(mockData, mockActions, mockConfig) as ISampleMessageProps<ISampleMessageData>;
  });
  it('renders correctly', () => {
    const component: renderer.ReactTestRenderer = renderer.create(
      <SampleMessage {...moduleProps} />
    );
    const tree: renderer.ReactTestRendererJSON | null = component.toJSON();
    expect(tree).toMatchSnapshot();
  });
});
