/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { IFeaturedLayoutData } from './featured-layout.data';
import { IFeaturedLayoutProps } from './featured-layout.props.autogenerated';

/**
 *
 * FeaturedLayout component
 * @extends {React.PureComponent<IFeaturedLayoutProps<IFeaturedLayoutData>>}
 */
export default class FeaturedLayout extends React.PureComponent<IFeaturedLayoutProps<IFeaturedLayoutData>> {
    public render(): JSX.Element {
        const { config, slots } = this.props;

        return (
            <div className={config.className}>
                <div className='row'>
                    <div className='col-lg-4 col-md-12'>
                        {slots.leftItem}
                    </div>
                    <div className='col-lg-8 col-md-12'>
                        <div className='row'>
                            <div className='col-lg-6 col-md-6'>
                            {slots.rightTopLeftItem}
                            </div>
                            <div className='col-lg-6 col-md-6'>
                            {slots.rightTopRightItem}
                            </div>
                            <div className='col-lg-12 col-md-12'>
                            {slots.rightBaseItem}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        );
    }
}
