/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { buildMockModuleProps} from '@msdyn365-commerce/core-internal';
/// <reference types="jest" />

// tslint:disable-next-line:no-unused-variable
import * as React from 'react';
import * as renderer from 'react-test-renderer';

import ProductList from '../product-list';
import { IProductListData } from '../product-list.data';
import {
  IProductListConfig,
  IProductListProps
} from '../product-list.props.autogenerated';

const mockData: IProductListData = {
  actionResponse: {
    text: 'Sample Response Data'
  }
};

const mockConfig: IProductListConfig = {
  showText: 'product-list'
};

const mockActions = {};

describe('ProductList', () => {
  let moduleProps: IProductListProps<IProductListData>;
  beforeAll(() => {
    moduleProps = buildMockModuleProps(mockData, mockActions, mockConfig) as IProductListProps<IProductListData>;
  });
  it('renders correctly', () => {
    const component: renderer.ReactTestRenderer = renderer.create(
      <ProductList {...moduleProps} />
    );
    const tree: renderer.ReactTestRendererJSON | null = component.toJSON();
    expect(tree).toMatchSnapshot();
  });
});
