/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { buildMockModuleProps} from '@msdyn365-commerce/core-internal';
/// <reference types="jest" />

// tslint:disable-next-line:no-unused-variable
import * as React from 'react';
import * as renderer from 'react-test-renderer';

import SampleButton from '../sample-button';
import { ISampleButtonData } from '../sample-button.data';
import {
  ISampleButtonConfig,
  ISampleButtonProps
} from '../sample-button.props.autogenerated';

const mockData: ISampleButtonData = {
  actionResponse: {
    text: 'Sample Response Data'
  }
};

const mockConfig: ISampleButtonConfig = {
  showText: 'sample-button'
};

const mockActions = {};

describe('SampleButton', () => {
  let moduleProps: ISampleButtonProps<ISampleButtonData>;
  beforeAll(() => {
    moduleProps = buildMockModuleProps(mockData, mockActions, mockConfig) as ISampleButtonProps<ISampleButtonData>;
  });
  it('renders correctly', () => {
    const component: renderer.ReactTestRenderer = renderer.create(
      <SampleButton {...moduleProps} />
    );
    const tree: renderer.ReactTestRendererJSON | null = component.toJSON();
    expect(tree).toMatchSnapshot();
  });
});
