/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { IProductContainerData } from './product-container.data';
import { IProductContainerProps } from './product-container.props.autogenerated';

/**
 *
 * ProductContainer component
 * @extends {React.PureComponent<IProductContainerProps<IProductContainerData>>}
 */
export default class ProductContainer extends React.PureComponent<IProductContainerProps<IProductContainerData>> {
    public render(): JSX.Element {
        const { slots } = this.props;

        return (
            <div className='row'>
                <h2 style={headingStyle} className="col-md-12">WOMAN</h2>
                {slots.slot1[0]}
                {slots.slot2[0]}
                {slots.slot3[0]}
            </div>
        );
    }
}


const headingStyle: React.CSSProperties = {
    textAlign: 'center',
    fontSize: '35px',
    marginTop: '30px',
    marginBottom: '60px',
    cursor: 'pointer'
}