/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

// import * as Msdyn365 from '@msdyn365-commerce/core';
import { IFeaturedCategoryData } from './featured-category.data';
import { IFeaturedCategoryProps } from './featured-category.props.autogenerated';

/**
 *
 * FeaturedCategory component
 * @extends {React.PureComponent<IFeaturedCategoryProps<IFeaturedCategoryData>>}
 */
export default class FeaturedCategory extends React.PureComponent<IFeaturedCategoryProps<IFeaturedCategoryData>> {
    public render(): JSX.Element {
        const {
            config: {
                categoryImage,
                categoryLink,
                buttonText
            }
        } = this.props;

        return (
            <div className='category-box'>
                <img src={categoryImage} alt={buttonText}/>
                <div className='category'>
                    <h4>{categoryLink.linkText}</h4>
                </div>
                <div className='box-inner'>
                    <h3>{categoryLink.linkText}</h3>
                    <ul>
                        <li><a href={categoryLink.linkUrl.destinationUrl}>{buttonText}</a></li>
                    </ul>
                </div>
            </div>
        );
    }
}
